### ISSUE TITLE
User tracking is very, very bad

### ISSUE THREAD

**Issue by fejx** [XXLJack/Wishify#18]
When a user disconnects, all his votes are gone due to the fact that the server is not able to recognize new users.
- [x] Implement newUuid function
- [x] Serverside UUID storage
- [x] Send each client information if he is owner rather than author info (Client + Serverside)
- [x] Clientside UUID storage
- [x] Connection message to handle UUID exchange and assignment
